# postgres-deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1  # Ajusta el número de réplicas según tus necesidades
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest  # Utiliza la imagen oficial de PostgreSQL
        env:
        - name: POSTGRES_DB
          value: peliculas
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: 123447a47f563e90fe2db0f56b1b17be62378e31b7cfd3adc776c59ca4c75e2fc512c15f69bb38307d11d5d17a41a7936789
        ports:
        - containerPort: 5432

